import { loadSettings, saveSettings } from '../../../lib/settings.js';

const SCHEMES: Record<string, string[]> = {
  cosmos: [
    'andromeda',
    'apollo',
    'aurora',
    'cassini',
    'comet',
    'cosmos',
    'eclipse',
    'galaxy',
    'horizon',
    'lunar',
    'mars',
    'nebula',
    'nova',
    'orbit',
    'phoenix',
    'pulsar',
    'quasar',
    'saturn',
    'solar',
    'stellar',
    'titan',
    'venus',
    'vega',
    'zenith',
  ],
  cities: [
    'amsterdam',
    'athens',
    'bangkok',
    'barcelona',
    'berlin',
    'cairo',
    'dublin',
    'florence',
    'havana',
    'istanbul',
    'kyoto',
    'lisbon',
    'london',
    'melbourne',
    'nairobi',
    'oslo',
    'paris',
    'prague',
    'rome',
    'seattle',
    'sydney',
    'tokyo',
    'vancouver',
    'vienna',
    'zurich',
  ],
  fruits: [
    'apple',
    'apricot',
    'banana',
    'blueberry',
    'cherry',
    'coconut',
    'fig',
    'grape',
    'guava',
    'kiwi',
    'lemon',
    'lime',
    'lychee',
    'mango',
    'melon',
    'orange',
    'papaya',
    'peach',
    'pear',
    'plum',
    'pomelo',
    'quince',
    'raspberry',
    'strawberry',
    'tangerine',
  ],
  music: [
    'allegro',
    'ballad',
    'bass',
    'blues',
    'bolero',
    'cadence',
    'chord',
    'crescendo',
    'drums',
    'encore',
    'forte',
    'fugue',
    'harmony',
    'jazz',
    'lyric',
    'melody',
    'opera',
    'piano',
    'rhythm',
    'samba',
    'sonata',
    'soprano',
    'symphony',
    'tempo',
    'waltz',
  ],
  gems: [
    'agate',
    'amber',
    'amethyst',
    'beryl',
    'coral',
    'crystal',
    'diamond',
    'emerald',
    'garnet',
    'jade',
    'jasper',
    'lapis',
    'malachite',
    'moonstone',
    'obsidian',
    'onyx',
    'opal',
    'pearl',
    'quartz',
    'ruby',
    'sapphire',
    'topaz',
    'tourmaline',
    'turquoise',
    'zircon',
  ],
  myths: [
    'apollo',
    'artemis',
    'athena',
    'atlas',
    'aurora',
    'cerberus',
    'diana',
    'echo',
    'freya',
    'griffin',
    'helios',
    'hermes',
    'iris',
    'juno',
    'loki',
    'medusa',
    'minerva',
    'neptune',
    'odin',
    'olympus',
    'orion',
    'pandora',
    'pegasus',
    'phoenix',
    'thor',
  ],
  ocean: [
    'anchor',
    'atoll',
    'barnacle',
    'coral',
    'current',
    'dolphin',
    'driftwood',
    'harbor',
    'island',
    'kelp',
    'lagoon',
    'lighthouse',
    'marina',
    'narwhal',
    'nautilus',
    'oyster',
    'pelican',
    'reef',
    'sailboat',
    'seashell',
    'squid',
    'starfish',
    'tide',
    'trident',
    'whale',
  ],
  spices: [
    'anise',
    'basil',
    'cardamom',
    'cayenne',
    'chili',
    'cinnamon',
    'clove',
    'coriander',
    'cumin',
    'dill',
    'fennel',
    'ginger',
    'juniper',
    'lavender',
    'mint',
    'nutmeg',
    'oregano',
    'paprika',
    'pepper',
    'rosemary',
    'saffron',
    'sage',
    'thyme',
    'turmeric',
    'vanilla',
  ],
  peaks: [
    'alps',
    'andes',
    'denali',
    'elbrus',
    'everest',
    'fuji',
    'hood',
    'kangchenjunga',
    'kazbek',
    'kilimanjaro',
    'logan',
    'makalu',
    'matterhorn',
    'mckinley',
    'mont-blanc',
    'olympus',
    'rainier',
    'shasta',
    'sierra',
    'sinai',
    'snowdon',
    'teton',
    'vesuvius',
    'whitney',
    'zion',
  ],
  dogs: [
    'akita',
    'beagle',
    'boxer',
    'bulldog',
    'collie',
    'corgi',
    'dingo',
    'doberman',
    'husky',
    'labrador',
    'malamute',
    'mastiff',
    'pinscher',
    'pointer',
    'poodle',
    'pug',
    'retriever',
    'rottweiler',
    'samoyed',
    'setter',
    'shepherd',
    'spaniel',
    'terrier',
    'vizsla',
    'whippet',
  ],
  dinos: [
    'ankylo',
    'bronto',
    'compy',
    'deinonychus',
    'diplo',
    'gallimimus',
    'iguanodon',
    'maia',
    'megalosaurus',
    'pachy',
    'parasaur',
    'plesio',
    'pterano',
    'raptor',
    'rex',
    'spinosaurus',
    'stego',
    'thero',
    'trice',
    'trodon',
    'utah',
    'veloci',
  ],
  cafe: [
    'affogato',
    'americano',
    'brew',
    'cappuccino',
    'chai',
    'cortado',
    'doppio',
    'espresso',
    'frappe',
    'latte',
    'lungo',
    'macchiato',
    'matcha',
    'mocha',
    'oolong',
    'pourover',
    'ristretto',
    'robusta',
  ],
};

const SCHEME_NAMES = Object.keys(SCHEMES);

export function assignScheme(repoId: string): string {
  const settings = loadSettings();
  if (settings.namingSchemes[repoId]) {
    return settings.namingSchemes[repoId];
  }

  const usedSchemes = new Set(Object.values(settings.namingSchemes));
  let scheme = SCHEME_NAMES.find((s) => !usedSchemes.has(s));
  if (!scheme) {
    scheme = SCHEME_NAMES[Math.floor(Math.random() * SCHEME_NAMES.length)];
  }

  saveSettings({
    namingSchemes: { ...settings.namingSchemes, [repoId]: scheme },
  });

  return scheme;
}

export function generateName(repoId: string, existingNames: string[]): string {
  const scheme = assignScheme(repoId);
  const pool = SCHEMES[scheme];
  const used = new Set(existingNames);

  const available = pool.filter((name) => !used.has(name));
  if (available.length > 0) {
    return available[Math.floor(Math.random() * available.length)];
  }

  // Fallback: append random suffix
  const base = pool[Math.floor(Math.random() * pool.length)];
  const suffix = Math.floor(Math.random() * 900) + 100;
  return `${base}-${suffix}`;
}
